// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApiMediator.Models
{
    public partial class People
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}